### ISSUE TITLE
Multiple choices for roles?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#50] opened 2020-01-29 12:18 UTC
Is it possible that a member of a project has multiple-roles, for example both data collector & data manager? Could we enable multiple choices for this question?

**Comment by korbinib** [comment] 2020-02-03 14:06
Not implemented in DSW yet

**Comment by korbinib** [comment] 2020-03-10 12:28
Duplicate of #17
related Jira issue [DSW-397](https://ds-wizard.atlassian.net/projects/DSW/issues/DSW-397)

**Closed as completed by korbinib** 2020-03-10 12:28 UTC
Labels: enhancement
